### PR TITLE
fix the class name reference of inner class of generics

### PR DESCRIPTION
**Pull request by kuzukami**
The asm library has a bug that the inner class name of generics class
cannot be correctly handled. I made a patch and some unit tests for this
problem.

### CODE REVIEW

**Comment by tcurdt** [comment]
Thanks a lot, @kuzukami. That's are quite some changes though. Do you have more details on that bug?

**Comment by kuzukami** [comment]
see the
'[ #317579 ] Signature Process in SignatureRemapper is Broken'
in
'
http://forge.ow2.org/tracker/?func=detail&aid=317579&group_id=23&atid=100023
'
.

Although the bug of the 'am' library will be fixed in near future by the
patch sent,
the 'jdependency' can avoid the bug by using an 'override' technique.


2015-07-27 16:29 GMT+09:00 Torsten Curdt <notifications@github.com>:

> Thanks a lot, @kuzukami <https://github.com/kuzukami>. That's are quite
> some changes though. Do you have more details on that bug?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tcurdt/jdependency/pull/8#issuecomment-125110208>.
>



-- 
株式会社 情報基盤開発
葛上昌司

〒113-0033
東京都文京区本郷7-3-1
東京大学アントレプレナープラザ
フリーダイヤル： 0120-922-552 (平日10:00～17:00)
FAX：03-6856-4600
URL：http://www.altpaper.net/

**Comment by kuzukami** [comment]
If you revert the 'DependenciesClassAdapter.java', the solution of this patch is totally disabled.

**Comment by tcurdt** [comment]
@kuzukami is this still relevant? Did they fix this in ASM itself?
I am about to release a new version that will use ASM6.

**Comment by tcurdt** [comment]
Closing due to lack of feedback. Most likely fixed in ASM anyway.

**Pull request closed without merging**
