### PR TITLE
Add a helper to remove identical classes for class clashes

### PR DESCRIPTION
**Pull request by CLandsberg**

### CODE REVIEW

**Comment by tcurdt** [comment]
Thanks!

**Comment by tcurdt** [comment]
Sorry, but I ended up rewriting quite a bit of this. It feels cleaner to me like this.
But it still needs some performance checking. It's slower than it should be.

**Comment by tcurdt** [comment]
Darn. My mistake. This can't work like that. This needs some more work.

**Comment by CLandsberg** [comment]
Thank you for your work. I am looking forward to the new release

**Pull request merged**
