### PR TITLE
Add related project to the README

### PR DESCRIPTION
**Pull request by cesarsotovalero**
Hi, this PR just adds [DepClean](https://github.com/castor-software/depclean) to he listed of related projects in the `README.md`.

### CODE REVIEW

**Comment by tcurdt** [comment]
Curious what has `depclean` that the `maven shade plugin` doesn't?
What does `depanalyzer` do that `jdependency` doesn't?

Do you also have a list of related projects somewhere?

**Comment by tcurdt** [comment]
Ping

**Comment by cesarsotovalero** [comment]
Hi @tcurdt,

> Curious what has depclean that the maven shade plugin doesn't?

The `maven-shade-plugin` repackages the project classes together with their dependencies into a single uber-jar, optionally renaming classes or removing unused classes as per the user specifications. 
DepClean, on the other hand, analyzes the dependency tree and provides a report of the dependencies used/unused.
DepClean provides a debloated version of the `pom.xml` file, and does not modifies the compiled classes. 

> What does `depanalyzer` do that `jdependency` doesn't?

DepClean is a Maven plugin. 
This means that it is executed during the `package` Maven build phase. 
DepClean works at the dependency level. 
This means that DepClean only reports about dependency usages, in contrast with `jdependency`, which works at the class file level. 

> Do you also have a list of related projects somewhere?

Yes, here is a list of related tools: https://www.cesarsotovalero.net/software-debloating-tools.html

**Comment by khmarbaise** [comment]
Why not using `maven-dependency-plugin:analyze` ? What is the difference?

**Comment by tcurdt** [comment]
Thanks for the clarification @cesarsotovalero 

Also thanks your list of related projects. Quite interesting.
Can you add a link back as well?

Mind blowing that none of the paper seem to mention `jdependency` which turns 14 years in a few weeks.

Might be a good idea to add a short description under the related projects.
I'll steel a few of you words for it if that's OK.

**Pull request merged**
