### PR TITLE
Fix Windows build

### PR DESCRIPTION
**Pull request by nielsbasjes**
I hope this fixes the build on Windows.

### CODE REVIEW

**Comment by tcurdt** [comment]
appveyor is just lovely 🙄

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.943 s
[INFO] Finished at: 2023-11-26T15:39:32Z
[INFO] ------------------------------------------------------------------------
...
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.vafer.jdependency.ClazzpathTestCase
[INFO] Tests run: 40, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.375 s -- in org.vafer.jdependency.ClazzpathTestCase
```
🤷‍♂️

I triggered another build but it seems stuck for the moment.

**Comment by tcurdt** [comment]
```
org.vafer.jdependency.ClazzpathUnitTestCase
[ERROR] org.vafer.jdependency.ClazzpathUnitTestCase.testShouldHaveUnitId -- Time elapsed: 0 s <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/projects/jdependency/target/test-classes/jar2.jar
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.vafer.jdependency.ClazzpathUnitTestCase.resourcePath(ClazzpathUnitTestCase.java:46)
	at org.vafer.jdependency.ClazzpathUnitTestCase.testShouldHaveUnitId(ClazzpathUnitTestCase.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
```

**Comment by nielsbasjes** [comment]
I'm going to install a Windows VM and figure this out.

**Comment by nielsbasjes** [comment]
@tcurdt It works now.

**Comment by tcurdt** [comment]
Seems like it's time for a release then.

**Comment by nielsbasjes** [comment]
@tcurdt When are you planning to do a release? I would like to continue my efforts at the maven shade plugin side.

**Comment by tcurdt** [comment]
Sorry, I dropped the ball here.
It's a new year - seems like another good reason to do this.

**Comment by tcurdt** [comment]
Just released 2.10.

**Pull request merged**
